import Head from "next/head";
import React, { lazy, Suspense, useState, useEffect } from "react";
const RemoteApp =
  typeof window !== "undefined"
    ? lazy(() => import("todo/TodoApp"))
    : () => null;

export default function Home() {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Rendering mfe:</h2>
      {isClient ? (
        <Suspense fallback={<div>Loading...</div>}>
          <RemoteApp />
        </Suspense>
      ) : null}
    </>
  );
}
